### ISSUE TITLE
Hello, In Section"5.3 Kinematic Skeleton Fitting","D = 29 is the number of degrees of freedom (DOF) for one skeleton", how D is calculated?

### ISSUE THREAD

**Issue by Han-Huaqiao** [mehtadushy/SelecSLS-Pytorch#10]
Hello, In Section"5.3 Kinematic Skeleton Fitting","D = 29 is the number of degrees of freedom (DOF) for one skeleton", how D is calculated?

**Comment by minhnhatvt** [comment]
Hi authors, thank you for the great work. I am having the same question. I would like to know what is the DoF for each joint in the skeleton? Is the design based on empirical evaluation or some previous study about the human kinematic structure? Thanks

**Comment by mehtadushy** [comment]
I don't recall off the top of my head, but if I recall correctly, the DOFs per joint are specified in one of the asset files that accompany the XNect software downloaded from the project page: https://gvv-assets.mpi-inf.mpg.de/xnect/
