### ISSUE TITLE
Hello,I have some question about dataset(i.e.,MuPoTS-3D and MPI-INF-3DHP dataset)

### ISSUE THREAD

**Issue by Han-Huaqiao** [mehtadushy/SelecSLS-Pytorch#11]
Now, MuPoTS-3D and MPI-INF-3DHP dataset only provide the download code of matlab, I would like to ask if these two data sets will also provide the download code of python or c++?  In addition， you will other cloud disk download links be provided (for example, Google Drive)？

**Comment by mehtadushy** [comment]
Only MATLAB code is provided, and hosting the data anywhere else and redistributing it is not allowed.
