### ISSUE TITLE
I have a problem when executing XNect C++ Library

### ISSUE THREAD

**Issue by Han-Huaqiao** [mehtadushy/SelecSLS-Pytorch#12]
When I execute XNect C++ Library and take our video  as input, an error is reported, 

terminate called after throwing an instance of'cv::Exception'
   what(): OpenCV(3.4.11) /action_recognition_project/XNect/opencv-3.4.11/modules/calib3d/src/solvepnp.cpp:754: error: (-215:Assertion failed) ((npoints >= 4) | | (npoints == 3 && flags == SOLVEPNP_ITERATIVE && useExtrinsicGuess)) && npoints == std::max(ipoints.checkVector(2, CV_32F), ipoints.checkVector(2, CV_64F)) in function'solvePnPGeneric'. 

Because the postCNNSecondNet function is encapsulated in libxnect.a file, I can’t see the implementation. How can I solve this error?

**Comment by mehtadushy** [comment]
Not relevant to this repo. Please send us an email.
