### ISSUE TITLE
user manual

### ISSUE THREAD

**Issue by EckCreek** [mehtadushy/SelecSLS-Pytorch#14]
Would it be possible to get a bit more detailed description on how to use the implementation. Specifically, I don't understand exactly which dataset to specify in the parameter (--imagenet_base_path <path_to_imagenet_dataset>).
I am a teacher and in the sense of a research transfer into the application practice I would be gladly ready to write a kind of user manual. But for that I would have to understand it myself first ;-)

**Comment by mehtadushy** [comment]
Hi

That script is meant for validating the accuracy of the model on the ImageNet image classification dataset. You need to download a copy and then specify the local path to the dataset. I hope this makes it clear
