### ISSUE TITLE
cuda version

### ISSUE THREAD

**Issue by XiaoJiNu** [mehtadushy/SelecSLS-Pytorch#3]
Hi, when I run evaluate_timing.py but appeared bugs as following
AssertionError: The NVIDIA driver on your system is too old (found version 9010).
Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version of the CUDA driver.

My cuda version of pytorch is 10.1 and I want to know what't the version of your cuda?

**Comment by mehtadushy** [comment]
Hi

The message pertains to your GPU driver, I think. You need to have a GPU driver version compatible with the cuda version your pytorch was compiled against.

**Comment by mehtadushy** [comment]
@XiaoJiNu 
Did you manage to resolve the issue on your end ?
