### ISSUE TITLE
code and weights of pose estimation

### ISSUE THREAD

**Issue by XiaoJiNu** [mehtadushy/SelecSLS-Pytorch#4]
Hi，thanks for your great work. Will you release the code and weights of human pose estimation? I'm very interested in training and evaluate code of stage I II III

**Comment by mehtadushy** [comment]
Hi

This repository is only meant to serve as a reference implementation of the network, such that people can use it for other tasks, and does not contain any material directly related to the paper. The pose aspects keep undergoing changes with review cycles, and we would only be able to release anything pose related once the paper is published. Any materials directly related to what is shown in the paper would be made available through a project webpage, and not be hosted on GitHub.

I would be happy to answer specific implementation questions though.
