### ISSUE TITLE
Bug in Usage section

### ISSUE THREAD

**Issue by jayakornv** [mehtadushy/SelecSLS-Pytorch#6]
Hi guys, thanks for the great work. 

Just wish to mention that I tried running the model based on the Usage guide and got `_pickle.UnpicklingError: invalid load key, '-'.` . I found the cause is in the `wget` command where the flag `-o` is used (this writes a log file to `./weights/` folder but actually saves the weight outside it). The good one should be `-O` (with capital O).

**Comment by mehtadushy** [comment]
Thanks for pointing it out!
It is fixed now.
