### ISSUE TITLE
Hello, will  pytorch code of the XNect project be released soon?

### ISSUE THREAD

**Issue by Han-Huaqiao** [mehtadushy/SelecSLS-Pytorch#8]
Hello, will pytorch code of the XNect project be released soon?

**Comment by lucaskingjade** [comment]
Same question

> Hello, will pytorch code of the XNect project be released soon?

Same Question.

**Comment by mehtadushy** [comment]
XNect was implemented in Caffe. We have not ported it to Pytorch.
